### ISSUE TITLE
Language highlight renders line numbers incorrectly in Safari (macOS)

### ISSUE THREAD

**Issue by jamesmartin** [pages-themes/time-machine#1]
Line numbers [render](https://pages-themes.github.io/time-machine/) above their associated syntax highlight block in Safari (10.0.1, macOS Sierra):

![screen shot 2016-12-14 at 1 55 01 pm](https://cloud.githubusercontent.com/assets/75904/21202880/2003f55a-c205-11e6-8263-e6c176c6301d.png)

<img width="396" alt="screen shot 2016-12-14 at 1 56 50 pm" src="https://cloud.githubusercontent.com/assets/75904/21202901/2f375f44-c205-11e6-95d8-cbc156087f35.png">

**Comment by eugmes** [comment]
Apparently Safari has problem with attribute "overflow: auto" on pre elements. The debugger shows that it comes from styles.css:1:854, but I cannot find it in the source code. If I disable this attribute either on block with line numbers or on block with the source code then everything is displayed fine. Replacing the value with anything but "visible" does not help.
