### ISSUE TITLE
jekyll complains about \xE2 character in time-machine.scss

### ISSUE THREAD

**Issue by mcr** [pages-themes/time-machine#4]
Setting my theme to time-machine on a fresh jekyll directory, I get:

      %bundle exec jekyll serve
     Configuration file: /corp/projects/pandora/minerva/www/_config.yml
            Source: /corp/projects/pandora/minerva/www
       Destination: /corp/projects/pandora/minerva/www/_site
    Incremental build: disabled. Enable with --incremental
      Generating... 
    Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Invalid US-ASCII character "\xE2" on line 475

The error is not in that file, which just does an @import of sass/jekyll-theme-time-machine.scss.
I'm not sure wha encoding that file is supposed to be in. Looks like maybe Latin-1?

    content: "‟";

Some kind of double-quote-ish symbol?
I replaced it with an actual double quote. Probably an &-escape character would be a better idea?

**Comment by benbalter** [comment]
@mcr if you google the "invalid US-ASCII character" error message, you can find several threads with users having similar issues with other SCSS files. I believe https://github.com/csswizardry/inuit.css/issues/270#issuecomment-56056606 is the solution.
