### ISSUE TITLE
Codeblocks are displaying incorrectly

### ISSUE THREAD

**Issue by advaith1** [pages-themes/time-machine#6]
![](https://cdn.discordapp.com/attachments/252296452708106240/388520005530157057/unknown.png)

This has been tested on Opera 51.0.2791.0 on Windows 10 and Firefox on Ubuntu.

**Comment by MV10** [comment]
Same problem is visible in Chrome 63.0.3239.84 on Win10.

**Comment by benbalter** [comment]
I believe this is a duplicate of https://github.com/pages-themes/time-machine/issues/1.

**Comment by advaith1** [comment]
@benbalter It's not, since that bug is safari only. In chrome I see this bug but not #1, so they must have different causes.

**Comment by aaaronic** [comment]
I also still see this exact bug on the demo site in Chrome 66 on MacOS Sierra.
