### ISSUE TITLE
Request: mobile-friendliness

### ISSUE THREAD

**Issue by advaith1** [pages-themes/time-machine#7]
Nowadays, many people access websites from their phones. Other GitHub Pages themes support mobile-friendliness, but Time Machine doesn't. This could be done by just showing the full width of the page when on mobile and extending the bottom of the page to the bottom of the phone screen.

**Comment by advaith1** [comment]
Does anyone want to try making the theme mobile friendly? I hope it eventually gets added.

**Comment by acbart** [comment]
It's unfortunate that the devs don't seem to care about the mobile experience. I had just assumed that any modern static site template would be responsive, but I guess that's not the case.
